// Code generated by "stringer -type=Error_Type"; DO NOT EDIT.

package joberrors

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Error_None-0]
	_ = x[Error_Panic-1]
	_ = x[Error_ConcurrentJob-2]
	_ = x[Error_DeferedJob-3]
}

const _Error_Type_name = "Error_NoneError_PanicError_ConcurrentJobError_DeferedJob"

var _Error_Type_index = [...]uint8{0, 10, 21, 40, 56}

func (i Error_Type) String() string {
	if i < 0 || i >= Error_Type(len(_Error_Type_index)-1) {
		return "Error_Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Error_Type_name[_Error_Type_index[i]:_Error_Type_index[i+1]]
}
