on: [ push, pull_request ]
name: Linter
jobs:
    lint:
        name: Lint project using GolangCI Lint
        runs-on: ubuntu-latest
        steps:
            -   name: Check out code into the Go module directory
                uses: actions/checkout@v1

            -   name: GolangCI-Lint Action
                uses: matoous/golangci-lint-action@v2
                with:
                    config: .golangci.yml
                    version: latest
                    only-new-issues: true
